services:

  backend:
    image: 753523293777.dkr.ecr.eu-north-1.amazonaws.com/cozy-loops-backend:latest
    container_name: cozy-loops-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: 753523293777.dkr.ecr.eu-north-1.amazonaws.com/cozy-loops-frontend:latest
    container_name: cozy-loops-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always